config circle yaml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,79 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/reference/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
-jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
-    docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
-      - image: cimg/base:current
+# Puedes habilitar orbs para sonar o node si quieres automatizar aún más
+orbs:
+  node: circleci/node@5.0.3
 
-    # Add steps to the job
-    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
+jobs:
+  build_and_test:
+    docker:
+      - image: cimg/node:18.17 # Imagen base Node.js
+    environment:
+      NODE_ENV: production
     steps:
-      # Checkout the code as the first step.
+      - checkout
+
+      - run:
+          name:  Instalar dependencias
+          command: |
+            echo " Instalando dependencias del proyecto..."
+            npm install
+
+      - run:
+          name: Compilar proyecto
+          command: npm run build
+
+      - run:
+          name: Ejecutar tests unitarios
+          command: npm run test
+
+      - run:
+          name: Análisis de código (ESLint)
+          command: |
+            echo " Ejecutando ESLint..."
+            npm run lint || echo " ESLint encontró errores, pero continuamos..."
+
+      - when:
+          condition:
+            matches:
+              pattern: ".*"
+              value: << pipeline.git.branch >>
+          steps:
+            - run:
+                name:  Análisis de calidad (SonarQube)
+                command: |
+                  if [ -f sonar-project.properties ]; then
+                    echo " Ejecutando análisis SonarQube..."
+                    npx sonar-scanner \
+                      -Dsonar.projectKey=nestd \
+                      -Dsonar.sources=src \
+                      -Dsonar.host.url=$SONAR_HOST_URL \
+                      -Dsonar.login=$SONAR_AUTH_TOKEN
+                  else
+                    echo " No se encontró archivo sonar-project.properties, omitiendo SonarQube..."
+                  fi
+
+  deploy:
+    docker:
+      - image: cimg/node:18.17
+    steps:
       - checkout
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name:  Despliegue
+          command: |
+            echo "Desplegando aplicación NestJS..."
+            npm install pm2 -g
+            pm2 delete all || true
+            pm2 start dist/main.js --name nestd
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  version: 2
+  build_and_deploy:
     jobs:
-      - say-hello
+      - build_and_test
+      - deploy:
+          requires:
+            - build_and_test
+          filters:
+            branches:
+              only: main
